services:
  file_host:
    image: nginx:latest
    ports:
        - "3000:80"
    restart: always
    volumes:
      - ./src:/src
      - ./nginx.conf:/etc/nginx/nginx.conf
  cron_pull:
    build: ./sync.Dockerfile
    command: cron -f
